FROM php:8.3-fpm AS base

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql

# Install dependencies
RUN apt-get update && apt-get -y install cron gettext-base moreutils zip && apt-get clean

# Configure Cron
COPY ./infrastructure/crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab
RUN touch /var/log/cron.log

FROM base AS dev
WORKDIR /app

RUN apt-get update && apt-get -y install git unzip

FROM base AS prod
WORKDIR /app

# Copy the application files
COPY . .
COPY infrastructure/entrypoint-prod.sh ./entrypoint.sh

# Install PHP dependencies
RUN composer install --no-dev --no-interaction --no-progress --optimize-autoloader