name: PHP CS Fixer

on:
  - push
  - pull_request

env:
  PHP_VERSION: '8.3'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Copy .env
      run: cp .env.dist .env
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
    - uses: php-actions/composer@v6
      name: Composer Install
      with:
        php_version: ${{ env.PHP_VERSION }}
        args: --ignore-platform-reqs
    - name: PHP CS Fixer
      run: bin/php-cs-fixer fix --dry-run